### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [papachan/data-covid19-colombia#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/ICCWOT
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by papachan** [comment]
@reeshmabijosh sure. if its metadata its easy for me.

**Comment by papachan** [comment]
@k-goncharova Done. i have generated an api token. My user is under the same nickname as my github account.

**Comment by k-goncharova** [comment]
Hello @papachan, thanks for ping. I've just given you the edit rights to your dataset. It would be helpful, if you could also add metadata like description and keywords to your dataset. It should take you 10-15 mins. You can check this dataset as an example https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL

**Comment by papachan** [comment]
@k-goncharova I am uploading every day a new dataset but i dont see it reflected at datasets.coronawhy.org. If someone could review it for me. And could we talk by email better?
